name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            zip unzip openjdk-17-jdk \
            python3-pip \
            build-essential \
            git \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            libreadline-dev \
            libgdbm-dev \
            liblzma-dev \
            tk-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.33
          pip install buildozer==1.5.0
          pip install python-for-android==2024.01.21

      - name: Force NDK Version
        run: |
          echo "android.ndk = 25b" >> buildozer.spec
          echo "android.minapi = 24" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
